### ISSUE TITLE
Add more stdlib functions

### ISSUE THREAD

**Issue by GearsDatapacks** [GMDU/code-of-copper#36]

**Comment by RevolvingMadness** [comment]
I haven't looked at docs if you already have these but some would be:
(Stolen from [here](https://docs.python.org/3/library/functions.html))
Non-Minecraft related:
abs(number) - Abs value of number
all(list) - All elements in list are true
any(list) - Any element in list is true

Minecraft related:
setGameRule(string, value) - Sets game rule
getGameRule(string) - Gets game rule

That's all idk how hard these are to imp

**Comment by GearsDatapacks** [comment]
#45 and #46 are more specific versions of this. This issue is not needed any more.
