### ISSUE TITLE
Additional Stdlib Functions

### ISSUE THREAD

**Issue by moxvallix** [GMDU/code-of-copper#50]
New additions since we divvied up the stdlib:
- [x] shuffle()
- [x] arr()
- [x] ascii()
- [x] char()
- [x] prefix?()
- [x] suffix?()
- [x] index() (edit to work with strings)
- [x] repeat()
- [x] replace()
- [x] split()
- [x] lower()
- [x] upper()
- [x] trim()
- [x] rtrim()
- [x] ltrim()
- [x] squeeze()
- [x] lpad()
- [x] rpad()
---
- [x] All documentation written
- [x] All tests written

**Comment by RevolvingMadness** [comment]
If the art function does what I think it does can't you just do:
```
x = 1
array = [x]
# Instead of
x = 1
array = arr(x)
```

**Comment by GearsDatapacks** [comment]
Then it doesn't do what you think it does

**Comment by moxvallix** [comment]
`arr()` constructs an array from a string or object.

Similar vein to `int()`, `obj()` and `str()`.

**Comment by RevolvingMadness** [comment]
Can you give me an example because I'm a little confused

**Comment by moxvallix** [comment]
`arr({a: 1, b: 2}) => [['a', 1], ['b', 2]]`
`arr("foo") => ["f", "o", "o"]`

**Comment by RevolvingMadness** [comment]
Okok I see
